添加了部分StandardPUP产品解析
CyanideCN/PyCINRAD pull request #92
Opened 2023-04-21 15:16 UTC by pysoer

添加了StandardPUP对OHP、HI、ET的解析。

2023-04-21 16:47 UTC, CyanideCN requested changes

2023-04-21 16:47 UTC, CyanideCN commented on cinrad/io/_dtype.py
> +PUP_HAIL_TABLE=[
标准格式的`dtype`全部放在cinrad/io/_radar_struct/standard_data.py里，变量名遵从规律可以叫`l3_hail_table`

2023-04-22 07:05 UTC, pysoer commented on cinrad/io/level3.py
> +        self.ptype_name = self.ptype_corr[self.ptype]
其他地方都修改好了，就这个dytpe和ptype没动。我后面找了些ROSE2.0的双偏振的产品来看，还有各种其他型号（例如一个“HCL_FMT”的产品，行标文件表7对应的数据类型竟然是37），下来研究透彻学习到位了再来处理吧，不急着删除，后面的双偏振的数据可能用得到。

2023-04-22 14:08 UTC, CyanideCN commented on cinrad/data/radar_station.json
> +    ],
这部分不属于本次pull request的内容，应该在另外pull request里添加

2023-04-22 14:08 UTC, CyanideCN commented on cinrad/io/_radar_struct/standard_data.py
> +l3_hail_table=[
这里和下面的等号旁边的空格都不太对，记得跑一遍`black`

2023-04-22 15:57 UTC, CyanideCN approved these changes

2023-04-24 10:41 UTC, merged